#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: Inhere
 * Date: 2017/3/23 0023
 * Time: 23:52
 * RUN  `server/ws_server`
 */

use Inhere\WebSocket\Application;
use Inhere\WebSocket\Http\Request;
use Inhere\WebSocket\Server\ClientMetadata;

define('PROJECT_PATH', __DIR__);

class Mgr {
    /** @var Application */
    public static $app;

    /**
     * @return Application
     */
    public static function app()
    {
        return self::$app;
    }
}

$loader = require __DIR__ . '/../../../autoload.php';
//var_dump(class_exists('\Inhere\Route\ORouter', 1));

$di = require __DIR__ . '/bootstrap.php';

$options = [
    'debug' => true,
    'driver' => '',
    'enableHttp' => true,
    'http' => [
        'docRoot' => __DIR__,
    ]
];
$app = new Application('', 9501, $options);

$app->onOpen(function (Application $app, Request $request, int $id) {
    $app->respond([
        'total' => $app->getWs()->count()
    ], 'welcome!');
});

$app->onClose(function (Application $app, int $id, ClientMetadata $client) {
    $app->respond([
        'total' => $app->getWs()->count()
    ]);
});

// websocket module
require __DIR__ . '/modules.php';

// http routes
//require __DIR__ . '/routes.php';

// start
$app->run();
