#!/usr/bin/env php
<?php

require __DIR__ . '/../../../autoload.php';

use inhere\webSocket\WSInterface;
use inhere\webSocket\server\ServerFactory;
use inhere\webSocket\server\ServerInterface;

$options = [
    'driver' => '',
];

// $ examples/server --driver streams
$opts = getopt('', ['driver:']);
$options['driver'] = $opts['driver'] ?? '';

$svr = ServerFactory::make('', 9501, $options);

$svr->on('open', function (ServerInterface $svr) {
    $svr->send('welcome!');
});

$svr->on(WSInterface::ON_MESSAGE, function (ServerInterface $svr, $data) {
    $svr->send("you input: $data");
});

$svr->start();
