#!/bin/env php
<?php

require __DIR__ . '/../../../autoload.php';

use inhere\webSocket\WebSocketClient;

$options = [
    'headers' => [
        'test-name' => 'value'
    ],
    'cookies' => [
        'test' => 'value',
        'test1' => 'value1',
    ]
];
$client = new WebSocketClient('ws://127.0.0.1:9501', $options);

vd($client->getSupportedWrappers(), $client->getSupportedTransports(), $client->getRequest()->toString());
