#!/bin/env php
<?php

require __DIR__ . '/../../../autoload.php';

use inhere\webSocket\client\drivers\StreamsDriver;
use inhere\webSocket\client\WebSocketClient;

$options = [
    'headers' => [
        'test-name' => 'value'
    ],
    'cookies' => [
        'test' => 'value',
        'test1' => 'value1',
    ]
];

$client = new StreamsDriver('ws://127.0.0.1:9501', $options);

$client->connect();

//$client->send('hello');

echo $client->receive();

$client->close();
