#!/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: Inhere
 * Date: 2017/3/23 0023
 * Time: 23:52
 * RUN  `server/ws_server`
 */

require __DIR__ . '/../../../autoload.php';

use inhere\webSocket\Application;
use inhere\webSocket\WebSocketServer;
use inhere\webSocket\parts\Request;

$app = new Application('', 9501);

$app->onOpen(function (Application $app, Request $request, int $id) {
    $app->respond([
        'total' => $app->getWs()->count()
    ], 'welcome!');
});

$app->onClose(function (Application $app, int $id, array $client) {
    $app->respond([
        'total' => $app->getWs()->count()
    ]);
});

$rootHandler = $app->route('/', new \inhere\webSocket\handlers\RootHandler());

// commands
$rootHandler->add('test', function ($data, $index, Application $app) {

    return 'hello';
});

// if use `$app->jsonDataParser()` client send: {"cmd":"login","name":"john","pwd":123456}
// if use `$app->complexDataParser()` client send: [@login]{"name":"john","pwd":123456}
$rootHandler->add('login', function ($data, $index, Application $app) {

    $name = $data['name'] ?? 'Please input your name.';

    $app->target($index)->respond("hello, $name. you login success");

    // 1. will return text
    // return "hello, $name";

    // 2. will return formatted json
    // return $app->fmtJson("hello, $name");

    // 3. will return data type by `Application::isJsonType()`.
    // `Application::isJsonType() === true`  return formatted json.
    // `Application::isJsonType() === false` return raw text.
    // **it is recommended**
    $app->respond("welcome new friend: $name join us.");
});

$rootHandler->add('logout', function ($data, $index, Application $app) {
    $user = $app->getUser($index);

    return $app->respond("goodbye, {$user['name']}");
});

// start
$app->run();
