<?php
/**
 * Created by PhpStorm.
 * User: inhere
 * Date: 2017-04-01
 * Time: 12:44
 */

namespace inhere\webSocket\client\drivers;

/**
 * Class StreamDriver
 * @package inhere\webSocket\client\drivers
 */
class StreamDriver extends AClientDriver
{
    /**
     * @var resource
     */
    protected $socket;

    /**
     * @inheritdoc
     */
    public static function isSupported()
    {
        return function_exists('stream_socket_accept');
    }

    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function connect($host, $port, $timeout = 0.1, $flag = 0)
    {

    }
}